name: Frontend

on:
    push:
      branches: [ main ]
      #paths:
        #- '.github/workflows/frontend.yml'
        #- 'bases/frontend/**'
        #- 'projects/cloudflare/**'
jobs:
  build:
    name: Build with shadow-cljs
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@11.0
        with:
          cli: 1.11.1.1347
      - name: Build the application
        run: |
            cd ./bases/worker
            npm ci
            npm run release
            ls -ls 
            ls -la out/
            cp -R public/ out/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: compilation
            path: ./bases/worker/out/

  deploy:
    name: Deploy the app
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Deploy frontend with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "4.7.0"
          workingDirectory: "./"
          # Deploying from the build output
          command: pages deploy ./out --project-name=aposter-frontend